version: "3"
services:
  who_review_me:
    build: .
    #image: shamkut/who_review_bot
    network_mode: host
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/Moscow
    volumes:
    - ./config:/usr/src/review/config
    - ./db:/usr/src/review/db
    restart: always
